# Generated by Django 4.1.7 on 2023-03-12 15:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='items',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=500, verbose_name='اسم المنتج')),
                ('quntity', models.IntegerField(verbose_name='الكميه ')),
                ('exporter', models.CharField(max_length=1000, verbose_name='المورد ')),
                ('data', models.DateField(auto_now_add=True)),
                ('time', models.TimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'المنتجات',
                'verbose_name_plural': 'المنتجات',
            },
        ),
        migrations.CreateModel(
            name='invntor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quntity', models.IntegerField(verbose_name='الكميه المنصرفه')),
                ('importer', models.CharField(max_length=500, verbose_name='المنصرف له')),
                ('data', models.DateField(auto_now_add=True)),
                ('time', models.TimeField(auto_now_add=True)),
                ('Items', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='inventor.items')),
            ],
            options={
                'verbose_name': 'المخزن',
                'verbose_name_plural': 'المخزن',
            },
        ),
    ]
