# Generated by Django 4.1.7 on 2023-03-09 19:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventor', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='invntor',
            name='user',
            field=models.CharField(default=1, max_length=500),
            preserve_default=False,
        ),
    ]
