# Generated by Django 4.1.7 on 2023-03-15 21:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('inventor', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invntor',
            name='Items',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='inventor.items', verbose_name='المنتج'),
        ),
        migrations.CreateModel(
            name='paydata',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('payer_name', models.CharField(max_length=5000, verbose_name='اسم المستلم')),
                ('quntity', models.IntegerField()),
                ('exporter', models.CharField(max_length=5000, verbose_name='اسم المسلم')),
                ('data', models.DateField(auto_now_add=True)),
                ('time', models.TimeField(auto_now_add=True)),
                ('items', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='inventor.items', verbose_name='المنتج')),
            ],
        ),
    ]
