# Generated by Django 4.1.7 on 2023-03-15 21:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inventor', '0002_alter_invntor_items_paydata'),
    ]

    operations = [
        migrations.DeleteModel(
            name='invntor',
        ),
    ]
