# Generated by Django 4.1.7 on 2023-03-15 22:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('inventor', '0003_delete_invntor'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='paydata',
            options={'verbose_name': 'الاذونات', 'verbose_name_plural': 'الاذونات'},
        ),
        migrations.AlterField(
            model_name='paydata',
            name='quntity',
            field=models.IntegerField(verbose_name='الكميه'),
        ),
        migrations.CreateModel(
            name='invntor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quntity', models.IntegerField(verbose_name='الكميه المنصرفه')),
                ('importer', models.CharField(max_length=500, verbose_name='المنصرف له')),
                ('data', models.DateField(auto_now_add=True)),
                ('time', models.TimeField(auto_now_add=True)),
                ('Items', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='inventor.items', verbose_name='المنتج')),
            ],
            options={
                'verbose_name': 'المخزن',
                'verbose_name_plural': 'المخزن',
            },
        ),
    ]
