# Generated by Django 4.1.7 on 2023-03-09 20:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inventor', '0003_alter_invntor_exporter_alter_invntor_name_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='invntor',
            old_name='user',
            new_name='importer',
        ),
    ]
