# Generated by Django 4.1.7 on 2023-03-15 22:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inventor', '0004_alter_paydata_options_alter_paydata_quntity_invntor'),
    ]

    operations = [
        migrations.RenameField(
            model_name='invntor',
            old_name='Items',
            new_name='items',
        ),
    ]
