# Generated by Django 4.1.7 on 2023-03-10 08:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventor', '0004_rename_user_invntor_importer'),
    ]

    operations = [
        migrations.CreateModel(
            name='items',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=500, verbose_name='اسم المنتج')),
                ('quntity', models.IntegerField(verbose_name='الكميه ')),
                ('exporter', models.CharField(max_length=1000, verbose_name='المورد ')),
            ],
        ),
        migrations.RemoveField(
            model_name='invntor',
            name='exporter',
        ),
    ]
