# Generated by Django 4.1.7 on 2023-03-10 08:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_alter_profile_options'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Profile',
        ),
    ]
